tools/client: Fix compiler errors
When trying to build the client on Fedora 24 with gcc version 6.2.1
20160916 (Red Hat 6.2.1-2) (GCC) I was met with the following

$ make
gcc -Wall -g -std=c99 -O2  -c nsleep.c -lrt
gcc -Wall -g -std=c99 -O2  -o client client.c nsleep.o -lrt
client.c: In function ‘main’:
client.c:53:18: error: storage size of ‘hints’ isn’t known
  struct addrinfo hints;
                  ^~~~~
client.c:79:27: error: invalid application of ‘sizeof’ to incomplete
type ‘struct addrinfo’
  memset(&hints, 0, sizeof(struct addrinfo));
                           ^~~~~~
client.c:82:2: warning: implicit declaration of function ‘getaddrinfo’
[-Wimplicit-function-declaration]
  getaddrinfo(SERVER, SERVER_PORT, &hints, &res);
  ^~~~~~~~~~~
client.c:84:21: error: dereferencing pointer to incomplete type ‘struct
addrinf’
  sockfd = socket(res->ai_family, res->ai_socktype, res->ai_protocol);
                     ^~
client.c:103:2: warning: implicit declaration of function ‘freeaddrinfo’
[-Wimplicit-function-declaration]
  freeaddrinfo(res);
  ^~~~~~~~~~~~
client.c:53:18: warning: unused variable ‘hints’ [-Wunused-variable]
  struct addrinfo hints;
                  ^~~~~
Makefile:7: recipe for target 'client' failed
make: *** [client] Error 1

Seems since glibc 2.22 we need to set _POSIX_C_SOURCE >= 201112L for
getaddrinfo(3) & freeaddrinfo(3) and this also takes care of struct
addrinfo.

Also make a note of what _XOPEN_SOURCE & _POSIX_C_SOURCE are needed for.

Signed-off-by: Andrew Clayton <andrew@zeta.digital-domain.net>